# conda env create -f environment.yml
name: lcls-cu-injector
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pydantic>2.3
  - botorch>=0.8.2
#  - lume-model>1.6.0 (not yet released version from pydantic_v2 branch)
  - ipywidgets
  - tqdm
  - matplotlib
